name = "discord-bot-hoyo-news"
main = "src/index.ts"
compatibility_date = "2024-02-08"

compatibility_flags = [ "nodejs_compat" ]
browser = { binding = "BROWSER" }

[limits]
cpu_ms = 10000

[triggers]
crons = [ "0 * * * *" ]

[[d1_databases]]
binding = "DB"
database_name = "discord-bot-hoyo-news"
database_id = "e2a77c43-85a2-4ffe-9b0d-75a8470db4cc"
